### ISSUE TITLE
Selecting datafile not suitable for munger throws ugly error

### ISSUE THREAD

**Issue by ericmtsai** [sfsinger19103/election_anomaly#47]
Better error handling when user picks a datafile not suitable for the munger
Traceback (most recent call last):
 File "election_anomaly/src/election_anomaly/main_routines/050_load_datafile.py", line 41, in <module>
  ui.new_datafile(sess,munger,d['results_file'],juris=juris,project_root=d['project_root'])
 File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/_init_.py", line 708, in new_datafile
 File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/munge_routines/_init_.py", line 38, in clean_raw_df
 File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 5697, in astype
  new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
 File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 582, in astype
  return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
 File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 442, in apply
  applied = getattr(b, f)(**kwargs)
 File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 625, in astype
  values = astype_nansafe(vals1d, dtype, copy=True)
 File "/usr/local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 874, in astype_nansafe
  return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
 File "pandas/_libs/lib.pyx", line 560, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for int() with base 10: ''
Steph-Airbook@MacBook-Pro-3 grr %

**Comment by sfsinger19103** [comment]
Still ugly fail (and ugliness probably depends on the discrepancy between the munger and the datafile):
```
>>> d.load_results()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/__init__.py", line 131, in load_results
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 608, in new_datafile
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 590, in read_datafile
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 928, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 915, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2070, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 155161, saw 4

>>> 
```

**Comment by sfsinger19103** [comment]
See also #85

**Comment by sfsinger19103** [comment]
Still ugly. This .par file (note CO munger)
```
[election_anomaly]
project_root=/Users/Steph-Airbook/Documents/CampaignScientific/NSF2019/State_Data/results_analysis/src/
rollup_directory=/Users/Steph-Airbook/Documents/CampaignScientific/NSF2019/State_Data/rollups_from_db
results_file=/Users/Steph-Airbook/Documents/Temp/nc_general/results_pct_20181106.txt
juris_name=NC
db_paramfile=/Users/Steph-Airbook/Documents/CampaignScientific/NSF2019/State_Data/database.par
munger_name=co_general18
db_name=NC_0708_v2
top_reporting_unit=North Carolina
sub_reporting_unit_type=county
```
yielded this error

```
>>> d.load_results()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Party____'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/__init__.py", line 134, in load_results
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 629, in new_datafile
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/munge_routines/__init__.py", line 389, in raw_elements_to_cdf
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/munge_routines/__init__.py", line 334, in munge_and_melt
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/munge_routines/__init__.py", line 95, in add_munged_column
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1760, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1270, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1387, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1963, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 624, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 3528, in xs
    return self[key]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1622, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Party____'
>>> 
```
