### ISSUE TITLE
New jurisdiction without folder errors badly

### ISSUE THREAD

**Issue by ericmtsai** [sfsinger19103/election_anomaly#51]
Running the program on a brand new jurisdiction (without creating jurisdiction folder myself first), got failure due to missing remark.txt:
```
WARNING: if necessary files are missing from the directory CA,
system may fail.
No subdirectory CA in /Users/singer3/PycharmProjects/results_analysis/src/jurisdictions. Here are the existing subdirectories:
   directory
0         MI
1      Phila
2         CO
3         FL
4  README.md
5         PA
6         NC
7         MD
Enter the number of the desired directory (or nothing, if your choice is not on the list):

Enter subdirectory name (alphanumeric and underscore only)
CA
Confirm creation of directory (y/n)?
/Users/singer3/PycharmProjects/results_analysis/src/jurisdictions/CA
y
Traceback (most recent call last):
  File "/Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/050_load_datafile.py", line 13, in <module>
    juris = ui.pick_juris_from_filesystem(d['project_root'],juris_name=d['juris_name'])
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 302, in pick_juris_from_filesystem
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/juris_and_munger/__init__.py", line 93, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/singer3/PycharmProjects/results_analysis/src/jurisdictions/CA/remark.txt'
cps-urbn650c-pk:Data_Loading singer3$ 
```

**Comment by sfsinger19103** [comment]
Errors appropriately reported:
```
>>> d = e.DataLoader(); d.check_errors()
(None, {'file_empty_errors': ['File {dictionary}.txt has just been created. Enter information in the file', 'File {ReportingUnit}.txt has just been created. Enter information in the file', 'File {Office}.txt has just been created. Enter information in the file', 'File {CandidateContest}.txt has just been created. Enter information in the file', 'File {Party}.txt has just been created. Enter information in the file', 'File {BallotMeasureContest}.txt has just been created. Enter information in the file', 'File {Election}.txt has just been created. Enter information in the file', 'File {Candidate}.txt has just been created. Enter information in the file', 'File {ExternalIdentifier}.txt has just been created. Enter information in the file'], 'directory_status': 'Directory {/Users/Steph-Airbook/Documents/CampaignScientific/NSF2019/State_Data/results_analysis/src/jurisdictions/PA_temp} created.'}, {'juris_created': False}, None, None)
```

**Comment by sfsinger19103** [comment]
Got error when jurisdiction directory contained all files except `remark.txt`:
```
>>> d = e.DataLoader(); d.check_errors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/__init__.py", line 37, in __init__
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 229, in pick_juris_from_filesystem
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/juris_and_munger/__init__.py", line 97, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Steph-Airbook/Documents/CampaignScientific/NSF2019/State_Data/results_analysis/src/jurisdictions/PA_temp/remark.txt'
>>> 
```
