### ISSUE TITLE
DB paramfile error

### ISSUE THREAD

**Issue by ericmtsai** [sfsinger19103/election_anomaly#52]
Ugly fail due to mistake in database parameter file (used database instead of dbname:
```
host=pgsql12.rc.pdx.edu
port=5432
database=election_data_science
...
```
Error message:
```
Traceback (most recent call last):
  File "/Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/050_load_datafile.py", line 16, in <module>
    error = dbr.establish_connection(paramfile=d['db_paramfile'],db_name=d['db_name'])
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/db_routines/__init__.py", line 85, in establish_connection
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extensions.py", line 160, in make_dsn
    "you can't specify both 'database' and 'dbname' arguments")
TypeError: you can't specify both 'database' and 'dbname' arguments
```

**Comment by sfsinger19103** [comment]
Works OK when error is in url (`localhostt`)
```
>>> d = e.DataLoader(); d.check_errors()
Unable to find database. Exiting.
Steph-Airbook@MacBook-Pro-3 State_Data % 
```

No error reported when dbname in database parameter file was misspelled (`postgresss`). Is that because the database named there is irrelevant? If so, that makes sense, and documentation should be updated. @ericmtsai let me know; then we just have to update documentation.

**Comment by ericmtsai** [comment]
Oh, ha. I didn't even have the `dbname` param in my `database.par` file. Old copy, perhaps? So I never built anything off of that. So I believe we just update the `database.par` template file and remove that line and we should be ready to go on this issue.

**Comment by sfsinger19103** [comment]
And `README.md` will need to be updated after feature-cleanup-interactivity is merged to `master`.
