### ISSUE TITLE
Ugly fail when user responds "y" to "Use existing record" in DataLoader.track_results()

### ISSUE THREAD

**Issue by sfsinger19103** [sfsinger19103/election_anomaly#76]
```
>>> d.track_results('pa_2018_g_results','2018 General')
Record already exists with value(s)
	pa_2018_g_results
in field(s)
	short_name
Use existing record (y/n?
y
Pick the _datafile record from the database:
          short_name                                          file_name  \
0  pa_2018_g_results  /Users/Steph-Airbook/Documents/CampaignScienti...   

  file_date download_date source  note  ReportingUnit_Id  Election_Id  
0       NaT           NaT   None  None              2512         3898  
Enter the number of the desired _datafile (or nothing, if your choice is not on the list):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "datafile_ux0"
DETAIL:  Key (short_name)=(pa_2018_g_results) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/db_routines/__init__.py", line 391, in save_one_to_db
  File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 2662, in to_sql
    method=method,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 521, in to_sql
    method=method,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1317, in to_sql
    table.insert(chunksize, method=method)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 755, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 669, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "datafile_ux0"
DETAIL:  Key (short_name)=(pa_2018_g_results) already exists.

[SQL: INSERT INTO _datafile (short_name, file_name, file_date, download_date, source, note, "ReportingUnit_Id", "Election_Id") VALUES (%(short_name)s, %(file_name)s, %(file_date)s, %(download_date)s, %(source)s, %(note)s, %(ReportingUnit_Id)s, %(Election_Id)s)]
[parameters: {'short_name': 'pa_2018_g_results', 'file_name': '/Users/Steph-Airbook/Documents/Temp/nc_general/results_pct_20181106.txt', 'file_date': None, 'download_date': None, 'source': None, 'note': None, 'ReportingUnit_Id': 2512, 'Election_Id': 3898}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/__init__.py", line 122, in track_results
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/db_routines/__init__.py", line 413, in save_one_to_db
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/munge_routines/__init__.py", line 271, in fk_plaintext_dict_from_db_record
TypeError: 'NoneType' object is not subscriptable
>>> 
```

**Comment by sfsinger19103** [comment]
See #79.
